[WIP] revamped DIO calibration routine architecture
DiCarloLab-Delft/PycQED_py3 pull request #621
Opened 2020-03-11 10:26 UTC by wvlothuizen

Please use the following template for a pull request. 

Fixes #issuenumber.

Changes proposed in this pull request:
- 
- 
-

@mention the name of someone you want to review this pull request. 

In order for the pull request to be merged, the following conditions must be met:
- travis test suite passes
- all reasonable issues raised by codacy must be resolved 
- a positive review is required

Whenever possible the pull request should
- follow the PEP8 style guide 
- have tests for the code
- be well documented and contain comments

Tests are not mandatory as this is generally hard to make for instruments that interact with hardware.

2020-09-18 11:31 UTC, wvlothuizen commented
the changes to UHFQuantumController.py look daunting because several functions were moved. I used https://www.diff-text.com/diff-text-combined-navigation.aspx and https://compare-text-files.com/downloads.html to verify that everything is OK.

2021-02-18 15:42 UTC, MiguelSMoreira requested changes
Fix issue in device object before merge

2021-02-18 15:42 UTC, MiguelSMoreira commented on pycqed/instrument_drivers/meta_instrument/device_object_CCL.py
> +        measured_qubits = ['X', 'D3', 'D4', 'Z1', 'D1']
Hack done locally in one of our setups, has to be reverted!

2021-02-18 15:44 UTC, MiguelSMoreira approved these changes

2021-02-18 15:55 UTC, merged