Make dio calibration of UHFQC compatible with LabOne 22.02
DiCarloLab-Delft/PycQED_py3 pull request #689
Opened 2022-03-21 11:03 UTC by martinr-zi

Fixes fixes #687

@schenfab, @mariosk-zi @michelecollodo

2022-03-21 13:37 UTC, mariosk-zi approved these changes

2022-03-21 15:26 UTC, schenfab requested changes
The nodes are not yet correctly used for the new scheme with >=22.02.

The old usage concept was along this line:
```
self.setd('raw/dios/0/delay', delay)
time.sleep(0.5)
[...]
error_timing = self.geti('raw/dios/0/error/timing')
```

The new concept should look like:
```
self.setd('raw/dios/0/delay', delay)
self.setd('raw/dios/0/error/timingclear', 0xffffffff) # clear the sticky timing error detection bits
time.sleep(0.5)
[...]
error_timing = self.geti('raw/dios/0/error/timingsticky') # readout timing errors that accumulated since the last call to "timingclear"
```

The important improvement here is the addition of the "timingclear" node, which is required to be manually set before checking for timing errors (by sleeping some time and reading the sticky timing error node afterwards). Previously, this clearing was done automatically by the device at arbitrary points in time, meaning reading the timing error node could have lead to false negatives (one would have got no timing errors, while actually there were some that were auto-cleared by the device just before reading the node).

Long story short: You first need to figure out if the old or new nodes are present, and then conditionally also set the "timingclear" node before sleeping... Probably by adding yet another try construct for the "timingclear" (except case would `pass` here), or maybe a bit more nicely, use listNodes beforehand to figure out which scheme is used and get rid of the try/excepts...

2022-03-21 15:46 UTC, schenfab approved these changes
LGTM, thanks for the change!

2022-07-07 08:29 UTC, wvlothuizen approved these changes
Looks good

2022-07-07 08:29 UTC, merged